spring.application.name=demo

spring.datasource.url=jdbc:h2:mem:demo
spring.h2.console.enabled=true
spring.sql.init.mode=always
spring.sql.init.encoding=utf-8

spring.jpa.hibernate.ddl-auto=create

# Naver API Keys
naver.api.client-id=9nT1EAZbhdVJWYrISlKV
naver.api.client-secret=S7RfHvdW1U
