# H2 ?????? ?? ???
spring.h2.console.enabled=true

# MyBatis ??
# SQL ??? ?? XML ?? ??
mybatis.mapper-locations=mappers/*.xml
# DTO ???? ??? ?? (XML?? ? ?? ?? ?? ?? ?? ??)
mybatis.type-aliases-package=com.example.project0820